#%RAML 1.0 DataType
properties:
          user: 
          password:
          accountNum:
            maxLength: 10
            minLength: 10
          bank:
            enum:
                  - ICIC
                  - AXIS
                  - HDFC