#%RAML 1.0 DataType
properties:
              accountNum:
                type: string
                minLength: 10
                maxLength: 10
              atmPin:
                type: string
                maxLength: 4
                minLength: 4
              ammountToWithdraw:
                type: number 
    